version: 0.2

env:
  parameter-store:
    DOCKER_HUB_USERNAME: "docker-hub-username"
    DOCKER_HUB_PASSWORD: "docker-hub-password"
    GITHUB_USERNAME: "github-username"
    GITHUB_TOKEN:    "github-token"

phases:
  install:
    commands:
      - chmod +x ./gradlew
  pre_build:
    commands:
      - export PROJECT_VERSION=v`egrep "^version" build.gradle | cut -f2 -d\'`
      - export BRANCH_TAG=`echo $CODEBUILD_SOURCE_VERSION | sed 's|/|-|g'`
      - echo Project version is ${PROJECT_VERSION}
      - echo Branch tag is ${BRANCH_TAG}
  build:
    commands:
      - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
      - docker login -u ${GITHUB_USERNAME} -p ${GITHUB_TOKEN} https://ghcr.io
      - docker build -t agonyforge/arbitrader:latest -f src/main/docker/codebuild/Dockerfile .
  post_build:
    commands:
      - echo "CodeBuild Initiator is ${CODEBUILD_INITIATOR}"
      - |
        if expr "${CODEBUILD_INITIATOR}" : "codepipeline*" >/dev/null; then
          docker tag agonyforge/arbitrader:latest agonyforge/arbitrader:latest
          docker tag agonyforge/arbitrader:latest agonyforge/arbitrader:${PROJECT_VERSION}
          docker tag agonyforge/arbitrader:latest ghcr.io/agonyforge/arbitrader:latest
          docker tag agonyforge/arbitrader:latest ghcr.io/agonyforge/arbitrader:${PROJECT_VERSION}
          docker push agonyforge/arbitrader:latest
          docker push agonyforge/arbitrader:${PROJECT_VERSION}
          docker push ghcr.io/agonyforge/arbitrader:latest
          docker push ghcr.io/agonyforge/arbitrader:${PROJECT_VERSION}
        elif expr "${CODEBUILD_INITIATOR}" : "GitHub*" >/dev/null; then
          docker tag agonyforge/arbitrader:latest agonyforge/arbitrader:${BRANCH_TAG}
          docker tag agonyforge/arbitrader:latest ghcr.io/agonyforge/arbitrader:${BRANCH_TAG}
          docker push agonyforge/arbitrader:${BRANCH_TAG}
          docker push ghcr.io/agonyforge/arbitrader:${BRANCH_TAG}
        else
          docker tag agonyforge/arbitrader:latest agonyforge/arbitrader:${BRANCH_TAG}
          docker tag agonyforge/arbitrader:latest ghcr.io/agonyforge/arbitrader:${BRANCH_TAG}
          docker push agonyforge/arbitrader:${BRANCH_TAG}
          docker push ghcr.io/agonyforge/arbitrader:${BRANCH_TAG}
        fi
      - printf '[{"name":"arbitrader","imageUri":"%s"}]' agonyforge/arbitrader:${PROJECT_VERSION} > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
